-- AlterTable
ALTER TABLE `listing` MODIFY `posteRecherche` ENUM('GARDIEN', 'DEFENSEUR_CENTRAL', 'DEFENSEUR_CENTRAL_DROIT', 'DEFENSEUR_CENTRAL_GAUCHE', 'LATERAL_DROIT', 'LATERAL_GAUCHE', 'MILIEU_DEFENSIF', 'MILIEU_CENTRAL', 'MILIEU_DROIT', 'MILIEU_GAUCHE', 'MILIEU_OFFENSIF', 'AILIER_DROIT', 'AILIER_GAUCHE', 'ATTAQUANT') NOT NULL;

-- AlterTable
ALTER TABLE `playerposition` MODIFY `poste` ENUM('GARDIEN', 'DEFENSEUR_CENTRAL', 'DEFENSEUR_CENTRAL_DROIT', 'DEFENSEUR_CENTRAL_GAUCHE', 'LATERAL_DROIT', 'LATERAL_GAUCHE', 'MILIEU_DEFENSIF', 'MILIEU_CENTRAL', 'MILIEU_DROIT', 'MILIEU_GAUCHE', 'MILIEU_OFFENSIF', 'AILIER_DROIT', 'AILIER_GAUCHE', 'ATTAQUANT') NOT NULL;
